version: "3.7"

services: 
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports: 
      - 5432:5432
    volumes: 
      - ./data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DATABASE: docker
    